server:
  shutdown: graceful

spring:
  application:
    name: 29cm-homework
  datasource:
    url: jdbc:mysql://localhost:3306/homework?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: homework
    password: password
    hikari:
      leak-detection-threshold: 1000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    database: mysql

  docker:
    compose:
      enabled: true
